# Generated by Django 5.0.14 on 2026-08-17 15:37

from django.db import migrations


DEFAULT_TOPICS = [
    "Berita Jakarta",
    "Wisata Jakarta",
    "Kuliner Jakarta",
    "Kata Kata Motivasi",
    "Fakta Unik Indonesia",
    "Tips Kehidupan",
    "Teknologi",
    "AI",
    "Digital Lifestyle",
    "Viral Indonesia",
]


def populate_topics(apps, schema_editor):
    Topic = apps.get_model("posts", "Topic")
    for name in DEFAULT_TOPICS:
        Topic.objects.get_or_create(name=name)


def remove_topics(apps, schema_editor):
    Topic = apps.get_model("posts", "Topic")
    Topic.objects.filter(name__in=DEFAULT_TOPICS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_topic"),
    ]

    operations = [
        migrations.RunPython(populate_topics, reverse_code=remove_topics),
    ]
