# Generated by Django 5.0.14 on 2026-08-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_populate_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('hidup', 'Hidup'), ('ai', 'AI & Teknologi'), ('astrology', 'Astrologi & Kosmologi')], default='hidup', max_length=20),
        ),
    ]
